import {
  Camera,
  Clock,
  Film,
  Heart,
  LayoutGrid,
  MapPin,
  Users,
} from "lucide-react";

// Sample gallery data
const galleryImages = [
  {
    id: 1,
    src: "/images/alireza.jpeg",
    title: "Mountain Sunset",
    date: "Dec 15, 2024",
    location: "Swiss Alps",
    favorite: true,
    album: "Nature",
  },
  {
    id: 2,
    src: "/images/alireza.jpeg",
    title: "Ocean Waves",
    date: "Dec 10, 2024",
    location: "Maldives",
    favorite: false,
    album: "Travel",
  },
  {
    id: 3,
    src: "images/alireza.jpeg",
    title: "City Nights",
    date: "Dec 5, 2024",
    location: "Tokyo",
    favorite: true,
    album: "Urban",
  },
  {
    id: 4,
    src: "/images/alireza.jpeg",
    title: "Autumn Forest",
    date: "Nov 28, 2024",
    location: "Vermont",
    favorite: false,
    album: "Nature",
  },
  {
    id: 5,
    src: "/images/alireza.jpeg",
    title: "Desert Dunes",
    date: "Nov 20, 2024",
    location: "Sahara",
    favorite: true,
    album: "Travel",
  },
  {
    id: 6,
    src: "images/alireza.jpeg",
    title: "Aurora Borealis",
    date: "Nov 15, 2024",
    location: "Iceland",
    favorite: true,
    album: "Nature",
  },
  {
    id: 7,
    src: "/images/alireza.jpeg",
    date: "Nov 10, 2024",
    location: "Studio",
    favorite: false,
    album: "People",
  },
  {
    id: 8,
    src: "images/alireza.jpeg",
    title: "Waterfall",
    date: "Nov 5, 2024",
    location: "Costa Rica",
    favorite: false,
    album: "Nature",
  },
  {
    id: 9,
    src: "/images/alireza.jpeg",
    title: "Modern Architecture",
    date: "Oct 30, 2024",
    location: "Dubai",
    favorite: true,
    album: "Urban",
  },
  {
    id: 10,
    src: "/images/alireza.jpeg",
    title: "Macro Flower",
    date: "Oct 25, 2024",
    location: "Garden",
    favorite: false,
    album: "Nature",
  },
  {
    id: 11,
    src: "images/alireza.jpeg",
    title: "Street Life",
    date: "Oct 20, 2024",
    location: "New York",
    favorite: true,
    album: "Urban",
  },
  {
    id: 12,
    src: "/images/alireza.jpeg",
    title: "Winter Peaks",
    date: "Oct 15, 2024",
    location: "Alps",
    favorite: false,
    album: "Nature",
  },
];

const sidebarCategories = [
  { id: "library", icon: LayoutGrid, label: "Library", count: 12 },
  { id: "recents", icon: Clock, label: "Recents", count: 8 },
  { id: "favorites", icon: Heart, label: "Favorites", count: 5 },
  { id: "people", icon: Users, label: "People", count: 3 },
  { id: "places", icon: MapPin, label: "Places", count: 6 },
];

const albumCategories = [
  {
    id: "nature",
    icon: Camera,
    label: "Nature",
    count: 5,
    color: "bg-green-500",
  },
  {
    id: "travel",
    icon: MapPin,
    label: "Travel",
    count: 3,
    color: "bg-blue-500",
  },
  { id: "urban", icon: Film, label: "Urban", count: 3, color: "bg-orange-500" },
  {
    id: "people",
    icon: Users,
    label: "People",
    count: 1,
    color: "bg-pink-500",
  },
];

export { albumCategories, galleryImages, sidebarCategories };
