import { Clock, Heart, Music2 } from "lucide-react";
import type { Playlist, Song } from "./music-types";

export const playlists: Playlist[] = [
  {
    id: "recently-added",
    name: "Recently Added",
    icon: <Clock className="h-4 w-4" />,
    count: 24,
  },
  {
    id: "favorites",
    name: "Favorites",
    icon: <Heart className="h-4 w-4" />,
    count: 47,
    color: "#ff2d55",
  },
  {
    id: "chill-vibes",
    name: "Chill Vibes",
    icon: <Music2 className="h-4 w-4" />,
    count: 32,
    color: "#5856d6",
  },
  {
    id: "workout",
    name: "Workout Mix",
    icon: <Music2 className="h-4 w-4" />,
    count: 18,
    color: "#ff9500",
  },
  {
    id: "focus",
    name: "Deep Focus",
    icon: <Music2 className="h-4 w-4" />,
    count: 21,
    color: "#34c759",
  },
];

export const songs: Song[] = [
  {
    id: "1",
    title: "Midnight City",
    artist: "M83",
    album: "Hurry Up, We're Dreaming",
    artwork: "/synthwave-album-art-neon-city.jpg",
    duration: 243,
    isFavorite: true,
  },
  {
    id: "2",
    title: "Starboy",
    artist: "The Weeknd",
    album: "Starboy",
    artwork: "/dark-r.jpg",
    duration: 230,
    isFavorite: false,
  },
  {
    id: "3",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    artwork: "/retro-80s-album-art-red-lights.jpg",
    duration: 201,
    isFavorite: true,
  },
  {
    id: "4",
    title: "Get Lucky",
    artist: "Daft Punk",
    album: "Random Access Memories",
    artwork: "/electronic-disco-album-art-chrome.jpg",
    duration: 369,
    isFavorite: true,
  },
  {
    id: "5",
    title: "Electric Feel",
    artist: "MGMT",
    album: "Oracular Spectacular",
    artwork: "/psychedelic-indie-album-art-colorful.jpg",
    duration: 229,
    isFavorite: false,
  },
  {
    id: "6",
    title: "Take On Me",
    artist: "a-ha",
    album: "Hunting High and Low",
    artwork: "/80s-synth-pop-album-art-sketch.jpg",
    duration: 225,
    isFavorite: true,
  },
  {
    id: "7",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    artwork: "/classic-rock-album-art-dramatic.jpg",
    duration: 354,
    isFavorite: true,
  },
  {
    id: "8",
    title: "Dreams",
    artist: "Fleetwood Mac",
    album: "Rumours",
    artwork: "/70s-rock-album-art-soft.jpg",
    duration: 257,
    isFavorite: false,
  },
];
